REFACTOR-#1934: move MultiIndex checks to backend
modin-project/modin pull request #1935
Opened 2020-08-19 20:41 UTC by ienkovich

## What do these changes do?
Another refactoring to move index accesses to backend to enable lazy computations

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1934 
- [ ] tests added and passing

2020-08-20 11:11 UTC, YarShev requested changes
I saw some more places where we can replace similar checks (both for columns and index) in order to avoid code inconsistencies. Can you please replace the corresponding checks?

2020-08-20 11:11 UTC, YarShev commented on modin/backends/base/query_compiler.py
> +            The axis to check.
```suggestion
            The axis to check (0 - index, 1 - columns).
```

2020-08-20 11:11 UTC, YarShev commented on modin/backends/pandas/query_compiler.py
> +        axis : 0 or 1
```suggestion
        axis : 0 or 1, default 0
```

2020-08-20 11:11 UTC, YarShev commented on modin/backends/pandas/query_compiler.py
> +            The axis to check.
```suggestion
            The axis to check (0 - index, 1 - columns).
```

2020-08-25 11:37 UTC, ienkovich commented
Thanks for your review! I added more checks using the new method and fixed docstrings.

2020-08-25 19:38 UTC, YarShev commented
@ienkovich , something went wrong with tests. Try to rebase in order to rerun tests.

2020-08-26 11:42 UTC, YarShev requested changes
@ienkovich , LGTM, but left one more minor comment regarding passing of parameter.

2020-08-26 11:42 UTC, YarShev commented on modin/pandas/base.py
> +            if not self._query_compiler.has_multiindex(axis):
```suggestion
            if not self._query_compiler.has_multiindex(axis=axis):
```

2020-08-26 11:44 UTC, YarShev requested changes

2020-08-26 11:44 UTC, YarShev commented on modin/backends/pandas/query_compiler.py
> +        if level is not None or self.has_multiindex(axis):
```suggestion
        if level is not None or self.has_multiindex(axis=axis):
```

2020-08-28 08:12 UTC, YarShev commented
@ienkovich , thanks, LGTM!

2020-08-28 08:12 UTC, YarShev approved these changes

2020-08-28 08:12 UTC, merged