DOC-REFACTOR: 1/n Refactoring the documentation
modin-project/modin pull request #2095
Opened 2020-09-17 04:56 UTC by aregm

- added the first touch for developer docs.
- added component diagrams

Signed-off-by: Melik-Adamyan, Areg <areg.melik-adamyan@intel.com>

2020-09-18 18:44 UTC, devin-petersohn requested changes
The commit message needs an open issue to pass the check. You can probably create one specific to this PR.

2020-09-18 18:44 UTC, devin-petersohn commented on docs/conf.py
> +issues_github_path = "modin-project/modin"
Missing newline at the end of the file

2020-09-18 18:44 UTC, devin-petersohn commented on docs/developer/architecture.rst
> +System Architecture
Do you want to delete the old version of the Architecture docs? Were there any changes from that?

2020-09-18 18:44 UTC, devin-petersohn commented on docs/developer/contributing.rst
> +Contributing
Same questions as above on original contributing docs.

2020-09-24 03:45 UTC, aregm commented on docs/developer/contributing.rst
> +Contributing
Ditto.

2020-09-24 03:46 UTC, aregm commented on docs/conf.py
> +issues_github_path = "modin-project/modin"
Fixed.

2020-09-24 20:03 UTC, devin-petersohn reviewed
Looks good!

2020-09-24 21:17 UTC, merged