Fix test_from_csv for simulated remote case
modin-project/modin pull request #2111
Opened 2020-09-21 13:17 UTC by vnlitvinov

## What do these changes do?
Both adapt local testing to possibility of having a remote proxy (by transferring the proxy by-value as low in the call hierarchy as possible) and by fixing `obj.__array__()` method.

With these changes applied, `python -m pytest --simulate-cloud=normal modin\pandas\test\test_io.py::test_from_csv` pass.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2100 
- [x] tests added and passing

2020-09-21 20:14 UTC, anmyachev requested changes
Also shouldn't you enable test `test_from_csv` in CI?

2020-09-21 20:14 UTC, anmyachev commented on modin/experimental/cloud/rpyc_proxy.py
> +            # import pdb;pdb.set_trace()
debug thing

2020-09-22 14:43 UTC, vnlitvinov commented on modin/experimental/cloud/rpyc_proxy.py
> +            # import pdb;pdb.set_trace()
removed

2020-09-22 15:16 UTC, anmyachev approved these changes
LGTM!

2020-09-22 15:47 UTC, merged