FIX-#2134: Fix mismatch partitioning insertions with same index
modin-project/modin pull request #2140
Opened 2020-09-24 12:01 UTC by devin-petersohn

Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

## What do these changes do?

Add a simple shuffle internal mechanism to have more performant insertions and concatenation when index objects already match.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #? 
- [x] tests added and passing

2020-09-25 03:49 UTC, aregm approved these changes

2020-09-25 03:49 UTC, aregm commented on modin/engines/base/frame/partition_manager.py
> +    def shuffle_simple(cls, axis, partitions, map_func, lengths):
Isn't it better to name simple_shuffle to match the data.py change?

2020-09-25 07:25 UTC, YarShev requested changes

2020-09-25 07:25 UTC, YarShev commented on modin/engines/base/frame/data.py
> +        Note: This should only be called when `other.axes[axis]` and `self.axes[axis]`
```suggestion
        Notes
        -----
        This should only be called when `other.axes[axis]` and `self.axes[axis]`
```

2020-09-25 07:25 UTC, YarShev commented on modin/engines/base/frame/data.py
> +        Note: This should only be called when `other.axes[axis]` and `self.axes[axis]`
`Notes` should be follow after `Returns`.

2020-09-25 07:25 UTC, YarShev commented on modin/engines/base/frame/data.py
> +                The BasePandasFrame to match to this object's partitioning
```suggestion
                The BasePandasFrame to match to self object's partitioning
```

2020-09-25 07:25 UTC, YarShev commented on modin/pandas/test/dataframe/test_indexing.py
> +    pandas_df["new"] = pd.Series(list(range(len(pandas_df))))
```suggestion
    pandas_df["new"] = pandas.Series(list(range(len(pandas_df))))
```

2020-09-25 07:25 UTC, YarShev commented on modin/engines/base/frame/partition_manager.py
> +        partitions = (
There is the function [axis_partition](https://github.com/modin-project/modin/blob/fe0afedd051f9aa721d27a63fcb8c67df32d9768/modin/engines/base/frame/partition_manager.py#L78) to get `column_partitions` or `row_partitions`. You need to merge with master before use this.

2020-09-25 15:25 UTC, YarShev commented
@devin-petersohn , I am okay with the changes but CI is red.

2020-09-25 16:27 UTC, devin-petersohn commented
@YarShev it looks like a Ray core dump in I/O which shouldn't have been touched by this. I restarted CI to see if it magically goes away.

2020-09-26 12:04 UTC, devin-petersohn commented
CI is red here looks like due to Omnisci. @ienkovich take a look?

2020-09-26 16:30 UTC, Garra1980 commented
And probably @dchigarev

2020-09-26 16:42 UTC, dchigarev commented
Conda failed to download packages because of a server error, I've re-run CI to see if it help

2020-09-26 19:11 UTC, dchigarev commented
@devin-petersohn @YarShev CI is green now

2020-09-26 19:17 UTC, YarShev approved these changes

2020-09-26 19:18 UTC, merged