FEAT-#2013: Sketch of improved merge_asof implementation
modin-project/modin pull request #2178
Opened 2020-09-30 19:26 UTC by itamarst

## What do these changes do?

This is a sketch of an approach to `merge_asof` that is more efficient than the current approach, hopefully.

@devin-petersohn would appreciate some feedback on e.g. which bits are potentially inefficient.

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #2013 (EVENTUALLY)
- [ ] tests added and passing

2020-10-06 15:37 UTC, itamarst commented
@devin-petersohn ping—if you have a chance, would love some feedback on this sketch before proceeding.

2020-10-14 13:26 UTC, devin-petersohn reviewed
Sorry for the delay in response, I took some vacation to rest. I'm still getting caught up.

The implementation here, while not super efficient, will be better than the current default behavior. We should still probably throw the warning for defaulting to pandas because we are collecting whole column(s) to the driver to compute the merge.

Otherwise it looks good until we can have a better internal way of joins with conditionals.

2020-11-02 15:26 UTC, itamarst commented
Will re-open when it's ready for review.

2020-11-05 19:46 UTC, itamarst commented
@devin-petersohn probably still needs testing of some of the fallback edge cases, but this is a lot closer to done, and so could use another passthrough.

So many edge cases... and I feel like I'm handling them in super-hacky ways.

2020-11-19 20:17 UTC, itamarst commented
@devin-petersohn any thoughts?

2020-11-20 15:13 UTC, devin-petersohn reviewed
This looks like a good approach given the current internals. Eventually, I would like to implement a non-equi join internally, which would fit this operator better.

2020-11-24 21:21 UTC, itamarst commented
Looks like:

1. Someone fixed the argument handling in `merge_asof` 17 days ago, so it'll be in Pandas 1.2.0.
2. There's a PR for one of the weird seeming argument combos: https://github.com/pandas-dev/pandas/issues/33463

2020-11-24 21:42 UTC, itamarst commented
@devin-petersohn I guess this is ready for review now? Main caveat I have is that example dataframes for tests were taken from Pandas docs, so potentially licensing issue that would need to fixed, not sure whether that's a problem or not.

2020-11-25 19:09 UTC, devin-petersohn requested changes
Looks good, a couple of minor points. Would you be able to fix the failing commitlint test?

2020-11-25 19:09 UTC, devin-petersohn commented on modin/pandas/general.py
> +            list(result.columns).index(left_on + suffixes[0]),
This avoids copying into a list
```suggestion
            result.columns.get_indexer_for([left_on + suffixes[0])[0],
```

2020-11-25 19:09 UTC, devin-petersohn commented on modin/pandas/general.py
> +    # List of columsn case should have been handled by direct Pandas fallback
```suggestion
    # List of columns case should have been handled by direct Pandas fallback
```

2020-11-30 16:57 UTC, itamarst commented
I can fix the commit by squash merging, my attempts at rebases have failed due to limits of my Git knowledge. So I can do that, or if you know you can do that. Perhaps the 70 character limit could be removed? It doesn't seem lack it adds much... :grin:

2020-11-30 17:09 UTC, devin-petersohn commented
Part of the 70 limit is a github thing, messages longer than that are chopped. I increased it to 88 in #2489.

2020-12-01 19:06 UTC, itamarst commented
OK, merged forward, hopefully everything will pass (once GitHub Actions gets unbroken for the day, I guess? Seems like they're having issues).

2020-12-04 16:47 UTC, itamarst commented
@devin-petersohn another frustrating git commit failure. I'm going to just turn this into a patch, and create a completely new PR with a new branch :(

2020-12-04 16:54 UTC, closed without merging