FIX-#2249: changed 'return' -> 'assert' in df_equals
modin-project/modin pull request #2250
Opened 2020-10-15 10:38 UTC by dchigarev

Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

2020-10-15 17:57 UTC, anmyachev requested changes

2020-10-15 17:57 UTC, anmyachev commented on modin/pandas/test/utils.py
> +            assert False
@dchigarev please add message

2020-10-15 17:57 UTC, anmyachev commented on modin/pandas/test/utils.py
> +            assert False
same

2020-10-15 21:13 UTC, dchigarev commented on modin/pandas/test/utils.py
> +            assert False
done

2020-10-15 21:13 UTC, dchigarev commented on modin/pandas/test/utils.py
> +            assert False
done

2020-10-16 08:01 UTC, anmyachev approved these changes
LGTM!

2020-10-16 08:02 UTC, merged