docs: fix simple typo, parition -> partition
modin-project/modin pull request #2573
Opened 2020-12-30 05:26 UTC by timgates42

There is a small typo in modin/engines/dask/pandas_on_dask/frame/partition.py, modin/engines/ray/pandas_on_ray/frame/partition.py.

Should read `partition` rather than `parition`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

2020-12-30 15:00 UTC, devin-petersohn requested changes
Thanks @timgates42!

You will need to reformat your commit to follow the contributing guidelines before it can be merged: https://modin.readthedocs.io/en/latest/contributing.html

2020-12-30 18:53 UTC, timgates42 commented
Thanks @devin-petersohn have signed off the commit

2020-12-31 21:41 UTC, devin-petersohn commented
@timgates42 is there an issue associated with this?

2021-01-04 19:29 UTC, timgates42 commented
Thanks @devin-petersohn added #2578

2021-01-05 15:13 UTC, devin-petersohn commented
@timgates42 thanks for opening the issue! I think it's still failing because of the commit message. We generate release notes from commit messages, so we have a standardized message format for the first line. The first line of the commit message should look something like:

```
DOCS-#2578: fix simple typo, parition -> partition
```

Does that make sense?

2021-01-05 20:04 UTC, timgates42 commented
Thanks @devin-petersohn adjusted the commit message

2021-01-05 23:29 UTC, devin-petersohn approved these changes
Thanks @timgates42! LGTM

2021-01-05 23:29 UTC, merged