FEAT-#2664: Add `to_labels` algebraic operator
modin-project/modin pull request #2666
Opened 2021-01-30 17:06 UTC by devin-petersohn

Resolves #2664

This add the algebraic operator for `to_labels`, which enables Modin to
better optimize the movement of data to metadata. See more in the paper
about the algebraic operator:
http://www.vldb.org/pvldb/vol13/p2033-petersohn.pdf

Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2664 
- [x] tests ~added and~ passing

2021-01-30 17:07 UTC, devin-petersohn commented
This does not include any performance enhancements at the moment, because we synchronously wait for the labels to be collected before moving on. A subsequent PR will have to be made if we want the materialization of the row labels to happen asynchronously.

2021-02-01 01:47 UTC, williamma12 requested changes
Looks good! Just very minor missing periods

2021-02-01 01:47 UTC, williamma12 commented on modin/backends/pandas/query_compiler.py
> +            # Add the names in the correct order
```suggestion
            # Add the names in the correct order.
```

2021-02-01 01:47 UTC, williamma12 commented on modin/engines/base/frame/data.py
> +            The list of column names to place as the new row labels
```suggestion
            The list of column names to place as the new row labels.
```

2021-02-01 01:47 UTC, williamma12 commented on modin/engines/base/frame/data.py
> +            A new BasePandasFrame that has the updated labels
```suggestion
            A new BasePandasFrame that has the updated labels.
```

2021-02-01 01:47 UTC, williamma12 commented on modin/backends/base/query_compiler.py
> +            Whether or not to drop the columns provided in the `keys` argument
```suggestion
            Whether or not to drop the columns provided in the `keys` argument.
```

2021-02-01 14:46 UTC, williamma12 approved these changes

2021-02-02 22:37 UTC, williamma12 approved these changes

2021-02-02 22:40 UTC, merged