FIX-#1263: Fix 'monotonic' implementation to allign new MapReduce beh…
modin-project/modin pull request #2683
Opened 2021-02-03 13:39 UTC by dchigarev

…avior

Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #1263 
- [ ] tests added and passing

2021-02-04 14:05 UTC, devin-petersohn requested changes
For `is_monotonic_increasing` and `is_monotonic_decreasing` we should probably be using window functions, which we do not currently have good support for.

We need an algebraic operator in the Modin dataframe layer, then we can just do a sliding window of size 2 for `is_monotonic`, follow by `all`. I don't think it can be done with the `MapReduce` approach and keep the correct metadata.

2021-02-04 16:22 UTC, dchigarev commented
@devin-petersohn we already can use window since there is a `.rolling` function in the Series API, the problem is that it seems that there is no standard function that allows us to determine is window monotonic or not, we can do it only with `.apply` by passing a lambda function that will compute it, but not all of the backends can execute UDFs python functions, so we can't do it this way. Looking forward, any implementation of the Window operator does not allow us to do this, since we forced to pass a lambda that determines that the window is monotonic.

2021-02-04 20:42 UTC, devin-petersohn commented
@dchigarev I think I was not clear about implementation details.

`is_monotonic_increasing` and `is_monotonic_decreasing` should be in the query compiler. From here, those functions should call the window algebraic operator in the Modin DataFrame. This algebraic operator has not been implemented yet, and we have been using `apply_full_axis` for it.

So should we wait until the window algebraic operator is available from Modin dataframe (which will be faster than apply) or implement with apply immediately? Do you have an opinion?

2021-02-04 21:05 UTC, dchigarev commented
@devin-petersohn what is the point then of using a rolling window if we can use `MapReduce`? I think that it would perform even slower than MapReduce since we need to apply `is_monotonic` to a `2*(len(ser)-1)` amount of windows. 

The current approach applies `is_monotonic` to every partition at the map phase and then do `all` on the results at reduce phase + apply `is_monotonic` to all of the edge elements of partitions that were memorized at the map phase. What's wrong with that logic and why do we need to replace it with a rolling window, that may involve much more computations?

2021-02-05 14:10 UTC, devin-petersohn commented
The main point is the correctness of doing window by hand with mapreduce vs a more general approach. The implementation of window will likely be very similar, but it will not require you to handle the corner cases as you do here, rather you can just call the algebraic operator with the is_monotonic function.

If you would like, you can generalize your approach here and we can add it to the Modin Dataframe layer. The window size will be important so we know how to handle the corner cases of window. We will want to reuse the window functionality for the other window functions for performance.

2021-10-03 13:51 UTC, devin-petersohn commented
@dchigarev what is the status of this PR? Should we close or do we plan to restart development?

2021-10-04 08:44 UTC, closed without merging