FIX-#2684: Add method level docs for Modin XGBoost
modin-project/modin pull request #2685
Opened 2021-02-03 14:34 UTC by prutskov

Signed-off-by: Alexey Prutskov <alexey.prutskov@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

2021-02-03 15:43 UTC, devin-petersohn requested changes

2021-02-03 15:43 UTC, devin-petersohn commented on docs/modin_xgboost.rst
> +``predict`` is separate function unlike ``xgboost.Booster.predict`` which uses an additional argument
```suggestion
``predict`` is separate function similar to ``xgboost.Booster.predict`` with an additional argument
```

2021-02-03 15:43 UTC, devin-petersohn commented on docs/modin_xgboost.rst
> +As you can see ``train`` has all arguments of ``xgboost.train`` function exclude the `evals_result`
```suggestion
``train`` has all arguments of ``xgboost.train`` function except for `evals_result`
```

2021-02-03 17:04 UTC, prutskov commented on docs/modin_xgboost.rst
> +``predict`` is separate function unlike ``xgboost.Booster.predict`` which uses an additional argument
fixed

2021-02-03 17:04 UTC, prutskov commented on docs/modin_xgboost.rst
> +As you can see ``train`` has all arguments of ``xgboost.train`` function exclude the `evals_result`
fixed

2021-02-03 18:18 UTC, devin-petersohn reviewed
Minor cleanup.

2021-02-03 18:18 UTC, devin-petersohn commented on docs/modin_xgboost.rst
> +``predict`` is separate function similar to ``xgboost.Booster.predict`` with an additional argument
```suggestion
``predict`` is similar to ``xgboost.Booster.predict`` with an additional argument, 
```

2021-02-03 18:18 UTC, devin-petersohn commented on docs/modin_xgboost.rst
> +``train`` has all arguments of ``xgboost.train`` function except for `evals_result`
```suggestion
``train`` has all arguments of the ``xgboost.train`` function except for ``evals_result``
```

2021-02-03 18:32 UTC, prutskov commented on docs/modin_xgboost.rst
> +``predict`` is separate function similar to ``xgboost.Booster.predict`` with an additional argument
Suggestion was applied.

2021-02-03 18:32 UTC, prutskov commented on docs/modin_xgboost.rst
> +``train`` has all arguments of ``xgboost.train`` function except for `evals_result`
Suggestion was applied.

2021-02-03 18:49 UTC, YarShev commented
Since we added `xgboost` to `requirements-dev.txt` and `environment-dev.yml` then `Install XGBoost on Modin` section of the doc page needs to be fixed.

2021-02-04 06:43 UTC, prutskov commented
@YarShev But we added `xgboost` only as development  dependency . `Install XGBoost on Modin section` is used for installing Modin for simple usage, and in this case we should say about needing of `xgboost` installation. For development dependencies we have instruction in [contributing](https://modin.readthedocs.io/en/latest/contributing.html#development-dependencies) docpage. What fixes do you mean?

2021-02-05 06:07 UTC, YarShev commented
I had thoughts on adding some notes of `xgb` to installation page. But I think now is not time to add it as dependency for simple Modin usage. So, we can leave it as it is now.

2021-02-05 06:08 UTC, YarShev approved these changes
~LGTM!~ xgboost needs to be added to reqs to build docs.

2021-02-08 13:30 UTC, prutskov commented
> ~LGTM!~ xgboost needs to be added to reqs to build docs.

added

2021-02-08 14:22 UTC, devin-petersohn approved these changes
LGTM!

2021-02-08 14:54 UTC, merged