FEAT-#2215: implement to_csv in a distributed way
modin-project/modin pull request #2715
Opened 2021-02-11 07:25 UTC by anmyachev

Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #2215 
- [ ] tests added and passing

2021-02-17 14:59 UTC, devin-petersohn requested changes
Just one question on the implementation, but overall looks great.

Can we add more inline documentation to the approach? For example, why return empty pandas.DataFrame() from the function? Please also try to remove several empty newline characters. Vertical whitespace should be use sparingly.

2021-02-17 14:59 UTC, devin-petersohn commented on modin/engines/ray/generic/io.py
> +        result = qc._modin_frame.broadcast_apply_full_axis(
Do we really need to use `broadcast_apply`? I think the regular `map_axis_partitions` would be better here.

2021-02-19 17:14 UTC, anmyachev commented
@devin-petersohn ready for review

2021-02-22 14:06 UTC, devin-petersohn approved these changes
Thanks @anmyachev, LGTM

2021-02-22 14:07 UTC, merged