DOCS-#3015: Document `modin.experimental.sklearn` module
modin-project/modin pull request #3016
Opened 2021-04-26 07:51 UTC by prutskov

Signed-off-by: Alexey Prutskov <alexey.prutskov@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

2021-04-28 07:50 UTC, prutskov commented
Built docs can be found here: https://modin--3016.org.readthedocs.build/en/3016/index.html

2021-04-29 14:27 UTC, vnlitvinov reviewed
Minor notes only

2021-04-29 15:16 UTC, prutskov commented on modin/experimental/sklearn/model_selection/train_test_split.py
> +        `train_size` will be 0.75.
Do you mean we need to add `FIXME` about changing parameter `**options`->`train_size=0.75`?

2021-04-29 15:18 UTC, prutskov commented on docs/flow/modin/experimental/sklearn.rst
> +This module holds experimental scikit-learn specific functionality for Modin.
fixed

2021-04-29 17:39 UTC, vnlitvinov commented on modin/experimental/sklearn/model_selection/train_test_split.py
> +        `train_size` will be 0.75.
yes

2021-04-29 18:53 UTC, prutskov commented on modin/experimental/sklearn/model_selection/train_test_split.py
> +        `train_size` will be 0.75.
added

2021-04-29 19:54 UTC, vnlitvinov approved these changes
LGTM

2021-05-05 00:53 UTC, devin-petersohn requested changes
Just one minor wording change for grammar. Thanks!

2021-05-05 00:53 UTC, devin-petersohn commented on docs/flow/modin/experimental/index.rst
> +Experimental part holds experimental functionality that is under development right now
```suggestion
``modin.experimental`` holds experimental functionality that is under development right now
```

2021-05-05 15:23 UTC, prutskov commented on docs/flow/modin/experimental/index.rst
> +Experimental part holds experimental functionality that is under development right now
fixed

2021-05-12 15:03 UTC, devin-petersohn approved these changes
Looks good @prutskov!

2021-05-12 15:04 UTC, merged