DOCS-#3204: Add a section regarding general rules for commiters
modin-project/modin pull request #3207
Opened 2021-07-02 11:30 UTC by YarShev

Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3204  
- [x] tests passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

2021-07-02 12:19 UTC, vnlitvinov commented on docs/contributing.rst
> +- Don't merge own PRs even If you are eligible to do it
```suggestion
- Don't merge your own PRs even if you are technically able to do it
```

2021-07-02 12:42 UTC, vnlitvinov submitted a review, later dismissed
LGTM

2021-07-02 16:24 UTC, devin-petersohn requested changes
A few minor rewordings, thanks for putting this in @YarShev!

2021-07-02 16:24 UTC, devin-petersohn commented on docs/contributing.rst
> +- Try to keep a PR name as much descriptive as possible
```suggestion
- Try to write a PR name as descriptive as possible.
```

2021-07-02 16:24 UTC, devin-petersohn commented on docs/contributing.rst
> +- Try to keep PRs as small as possible. One PR should be making one semantically atomic change
```suggestion
- Try to keep PRs as small as possible. One PR should be making one semantically atomic change.
```

2021-07-02 16:24 UTC, devin-petersohn commented on docs/contributing.rst
> +- Don't merge your own PRs even if you are technically able to do it
```suggestion
- Don't merge your own PRs even if you are technically able to do it.
```

2021-07-05 09:57 UTC, vnlitvinov approved these changes
LGTM

2021-07-20 07:40 UTC, YarShev commented
@devin-petersohn , reminder

2021-07-21 13:34 UTC, devin-petersohn approved these changes
Thanks @YarShev!

2021-07-21 13:34 UTC, merged