FIX-#3659: specify `max_retires=0` for `to_csv` function
modin-project/modin pull request #3660
Opened 2021-11-06 16:47 UTC by anmyachev

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #3659 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

2021-11-09 10:48 UTC, anmyachev commented
@devin-petersohn please review

2021-11-09 11:16 UTC, vnlitvinov requested changes

2021-11-09 11:16 UTC, vnlitvinov commented on modin/core/execution/ray/generic/io/io.py
> +            max_retries=0,
This is a separate change. Please limit this PR to only adding _ability_ to pass extra keywords, and use them separately (you could use that in the `to_csv`-hang-fixing PR after this one is merged).

2021-11-09 16:57 UTC, vnlitvinov approved these changes
LGTM!

2021-11-15 16:23 UTC, anmyachev commented
@devin-petersohn friendly reminder about review :)

2021-11-15 20:03 UTC, devin-petersohn approved these changes
LGTM

2021-11-15 20:06 UTC, merged