FEAT-#3724: Converting self.resample_args for Resampler into a dict
modin-project/modin pull request #3738
Opened 2021-11-25 19:29 UTC by Rubtsowa

Signed-off-by: Maria Rubtsova <maria.rubtsova@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #3724 ? 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

2021-11-25 20:59 UTC, vnlitvinov requested changes

2021-11-25 20:59 UTC, vnlitvinov commented on modin/pandas/base.py
> +        self.resample_args = {
pls rename the attribute to be consistent to `self.resample_kwargs`

2021-11-25 20:59 UTC, vnlitvinov commented on modin/pandas/base.py
> +            return Resampler(self._dataframe[key], **self.resample_args)
I think @YarShev was against my simplification - this indeed makes it harder to make a subclass if we create `Resampler` explicitly

2021-11-26 06:54 UTC, YarShev commented on modin/pandas/base.py
> +        self.resample_kwargs = {
The comment above should be removed.

2021-11-26 09:25 UTC, vnlitvinov approved these changes
LGTM

2021-11-26 10:10 UTC, YarShev commented
@Rubtsowa , we should probably add the changes to BaseQueryCompiler too since it seems the CI job failed because of that.

2021-11-26 12:25 UTC, vnlitvinov commented
> @Rubtsowa , we should probably add the changes to BaseQueryCompiler too since it seems the CI job failed because of that.

I don't see any CI failures here, what are you talking about?

2021-11-27 13:17 UTC, vnlitvinov approved these changes
LGTM

2021-11-29 09:28 UTC, YarShev commented
All entries `resample_args : list` -> `resample_kwargs : dict` need to be replaced in base QC.

2021-11-29 09:58 UTC, vnlitvinov approved these changes
LGTM assuming CI passes!

2021-11-29 09:59 UTC, vnlitvinov commented
> All entries `resample_args : list` -> `resample_kwargs : dict` need to be replaced in base QC.

Good catch!

2021-11-29 10:55 UTC, YarShev approved these changes

2021-11-29 13:33 UTC, merged