TEST-#3869: add build-docs check in CI
modin-project/modin pull request #3870
Opened 2021-12-18 21:34 UTC by anmyachev

Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #3869 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

2021-12-20 13:17 UTC, anmyachev commented on docs/getting_started/troubleshooting.rst
> +  # Aborted (core dumped)
These lines did not allow to recognize that this is a block of python code.

2021-12-20 13:18 UTC, anmyachev commented on docs/getting_started/faq.rst
> +see :doc:`out-of-memory support </getting_started/out_of_core>` for Modin.
Invalid link

2021-12-20 13:23 UTC, anmyachev commented on docs/flow/modin/experimental/pandas.rst
> -   :members: to_pickle_distributed
Thus, the library generated 2 targets with the same `DataFrame` name, which resulted in a warning. (`...\projects\modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.var:: WARNING: more than one target found for cross-reference 'DataFrame': modin.experimental.pandas.DataFrame, modin.pandas.dataframe.DataFrame`)

2021-12-20 13:34 UTC, dchigarev requested changes

2021-12-20 13:34 UTC, dchigarev commented on .github/workflows/ci.yml
> +      - run: cd docs && sphinx-build -b html . build
```suggestion
      - run: cd docs && sphinx-build -T -E -b html . build
```
1. `-T` should [increase verbosity](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-T) if something goes wrong.
2. `-E` [ensures](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-E) that we're not using any cache.

2021-12-20 13:45 UTC, dchigarev approved these changes
LGTM!

2021-12-20 17:27 UTC, anmyachev commented
@modin-project/modin-core let's merge if no other comments :)

2022-01-12 17:07 UTC, devin-petersohn approved these changes

2022-01-12 17:07 UTC, merged