DOCS-#4545: Add socials to README
modin-project/modin pull request #4555
Opened 2022-06-08 21:19 UTC by jeffreykennethli

Signed-off-by: jeffreykennethli <jkli@ponder.io>

Adds pepy link for total Modin downloads, moves Slack and Discourse to a separate table so users know which socials they should join if so willing, and add a link to the Modin project Twitter.

The rationale for Slack -> Dev Community & Support and Discourse -> Community Questions is that Slack allows us to offer dev support in real-time, and surface updates (as does Twitter) like new releases. Discourse is good as a repo of questions people have, like StackOverflow.

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #4545  
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

2022-06-09 00:05 UTC, dorisjlee commented
Thanks @jeffreykennethli! Can we put the grid above the list of badges? Both the badges and the grid should be centered (like the header up top).

2022-06-09 01:16 UTC, jeffreykennethli commented
Moved the table above the badges, and centered the badges. Unfortunately, Github-flavored markdown doesn't allow centering the entire table, as the table is rendered as "filled" by default, see https://stackoverflow.com/a/44233457/19027728

Some options are:
* leave the table as is
* reformat the table so that each row contains a badge, purpose, description, etc. to fill the width
* remove the table, and replace it with a short line describing ways to connect with Modin Developers. Something like "Join the Modin community on Slack for active dev support and updates." Then combine the Discourse and Twitter badges with the remaining badges.

2022-06-09 01:39 UTC, RehanSD commented
> Moved the table above the badges, and centered the badges. Unfortunately, Github-flavored markdown doesn't allow centering the entire table, as the table is rendered as "filled" by default, see https://stackoverflow.com/a/44233457/19027728
> 
> 
> 
> Some options are:
> 
> * leave the table as is
> 
> * reformat the table so that each row contains a badge, purpose, description, etc. to fill the width
> 
> * remove the table, and replace it with a short line describing ways to connect with Modin Developers. Something like "Join the Modin community on Slack for active dev support and updates." Then combine the Discourse and Twitter badges with the remaining badges.

I think it may be possible to do if you use HTML instead of markdown, like we do for the badges at the top of the readme? The link you sent also seems to indicate that that may be possible!

2022-06-09 01:55 UTC, jeffreykennethli commented
> I think it may be possible to do if you use HTML instead of markdown, like we do for the badges at the top of the readme? The link you sent also seems to indicate that that may be possible!

Yup! Was able to do this after all.

2022-06-09 03:05 UTC, dorisjlee requested changes

2022-06-09 03:05 UTC, dorisjlee commented on README.md
> +Dev Community & Support (<1 day response) | Forums | Socials |
I don't know if we can promise <24 hr response, esp with timezones, etc.

```suggestion
Dev Community & Support | Forums | Socials |
```

2022-06-09 03:05 UTC, dorisjlee commented on README.md
> +| <a href='https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA'><img src='https://img.shields.io/static/v1?label=chat&logo=slack&message=Slack&color=brightgreen' a
Do some of the buttons appear oversized for you compared to the Twitter one?
![Screen Shot 2022-06-08 at 8 01 47 PM](https://user-images.githubusercontent.com/5554675/172755101-32bac225-2acb-4325-a192-dd41fe07cc49.png)

2022-06-09 03:05 UTC, dorisjlee commented on README.md
> +| <a href='https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA'><img src='https://img.shields.io/static/v1?label=chat&logo=slack&message=Slack&color=brightgreen' a
Should we moves docs up here too or keep just the socials?

2022-06-09 03:05 UTC, dorisjlee commented on README.md
> +| <a href='https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA'><img src='https://img.shields.io/static/v1?label=chat&logo=slack&message=Slack&color=brightgreen' a
I could imagine the grid being any links that are "actionable" while the badges are more around metrics.

2022-06-09 15:03 UTC, jeffreykennethli commented on README.md
> +| <a href='https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA'><img src='https://img.shields.io/static/v1?label=chat&logo=slack&message=Slack&color=brightgreen' a
I considered that ordering as well. I will add Docs to the table and we can compare.

2022-06-09 21:55 UTC, mvashishtha commented
@jeffreykennethli  Thank you for doing this! Should we get rid of the line between the Modin slogan and the links table? 
![Screen Shot 2022-06-09 at 4 53 22 PM](https://user-images.githubusercontent.com/10712109/172951891-9d83f667-f87b-4523-9fe7-795aba386a78.png)

2022-06-09 22:11 UTC, jeffreykennethli commented
> @jeffreykennethli Thank you for doing this! Should we get rid of the line between the Modin slogan and the links table?

Sure @mvashishtha! It would involve changing a `h2` to `h3` which removes the line and makes the text slightly (imo barely perceptible) smaller. Is that all right? See: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#h2 for reference.

2022-06-09 22:13 UTC, mvashishtha commented
> > @jeffreykennethli Thank you for doing this! Should we get rid of the line between the Modin slogan and the links table?
> 
> Sure @mvashishtha! It would involve changing a `h2` to `h3` which removes the line and makes the text slightly (imo barely perceptible) smaller. Is that all right? See: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#h2 for reference.

I prefer h2 then, because I want the h2 text size.

2022-06-12 22:27 UTC, RehanSD requested changes
Looks good to me, but quick, minor, question - why is the name + logo not consistent across the discourse + slack buttons?
<img width="489" alt="image" src="https://user-images.githubusercontent.com/17012605/173255963-7a0e42cb-2d65-401c-95d7-9c9d9706fb71.png">
in the picture above, the slack button has chat near the logo, and slack on the right side in the green, but the discourse button has discourse near the logo, and forum on the right side in the purple. I think it would be good to standardize this across buttons, or just get rid of it entirely (since having forum in the button and the table column header is slightly repetitive). If the second option is possible, and we do end up going with it, I think maybe just having the whole button be green and having the Slack logo + Slack for the slack button, and having the discourse button be purple and having the discourse logo + discourse would look nice!

Example Mockup:
![image](https://user-images.githubusercontent.com/17012605/173256132-40d614a1-4895-44a4-8c93-befca11f0b1a.png)

2022-06-15 13:51 UTC, jeffreykennethli commented
@RehanSD I agree with your points about "chat" and "forum" being unnecessary. I changed the Slack badge to one that doesn't have the "chat" text, but didn't find a Discourse badge that looked like your mockup. Instead I used a badge from here: https://shields.io/category/chat (you can see Discourse has a few badge options, I went with status). We can also create our own Discourse badge if you think it's worth it.

2022-06-21 15:29 UTC, devin-petersohn reviewed
I prefer to route people to the Slack instead of discourse. What do you think?

2022-06-21 15:29 UTC, devin-petersohn commented on README.md
> +| [![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA) | <a hr
```suggestion
| [![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://join.slack.com/t/modin-project/shared_invite/zt-yvk5hr3b-f08p_ulbuRWsAfg9rMY3uA) | [![Stack Overflow](https://img.shields.io/badge/-Stackoverflow-FE7A16?style=for-the-badge&logo=stack-overflow&logoColor=white)](https://stackoverflow.com/questions/tagged/modin) | <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/modin_project?style=social" height=28 align="center"> | <a href="https://modin.readthedocs.io/en/latest/?badge=latest"><img alt="" src="https://readthedocs.org/projects/modin/badge/?version=latest" height=28 align="center"></a> |
```

2022-06-21 20:40 UTC, RehanSD submitted a review, later dismissed
LGTM! Should we add something to the release notes for this?

2022-06-21 20:45 UTC, RehanSD approved these changes
LGTM!

2022-06-23 08:31 UTC, YarShev commented on README.md
> -<a href="https://discuss.modin.org"><img alt="" src="https://img.shields.io/badge/discourse-forum-purple.svg?logo=discourse&logoColor=white" align="center"></a>
If it is intended not to bloat the table, that is okay to me. Just to be informed please point me at the related discussion or comment.

2022-06-23 19:50 UTC, YarShev approved these changes

2022-06-23 19:52 UTC, merged