FIX-#4564: Register custom serializer to avoid Ray race condition
modin-project/modin pull request #4568
Opened 2022-06-10 14:24 UTC by devin-petersohn

Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #4564  
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

2022-06-10 16:36 UTC, RehanSD submitted a review, later dismissed
LGTM! Pleased to release notes!

2022-06-10 17:58 UTC, YarShev reviewed
Please fix the PR title, link an issue to be resolved and add a release note with your GH nickname.

2022-06-10 17:58 UTC, YarShev commented on modin/core/execution/ray/common/utils.py
> +    ray.util.register_serializer(
I think we should add a comment on why we do this.

2022-06-10 19:52 UTC, mvashishtha commented
@devin-petersohn You have "customer" instead of "custom" in the PR title and first commit description.

2022-06-10 19:53 UTC, mvashishtha approved these changes
LGTM, Thanks!

2022-06-10 19:53 UTC, RehanSD approved these changes
LGTM! We should conduct a perf check to see how `pickle` compares to Ray's serializer.

2022-06-10 19:54 UTC, devin-petersohn commented
>@devin-petersohn You have "customer" instead of "custom" in the PR title and first commit description.

:rofl: fixed

2022-06-10 19:55 UTC, mvashishtha commented
@devin-petersohn "customer" is still in the first commit description. It's fine by me to leave it that way.

2022-06-10 19:55 UTC, RehanSD requested changes
Please add your name to the contributors in the release notes!

2022-06-10 19:56 UTC, YarShev commented on docs/release_notes/release_notes-0.16.0.rst
> +  * FIX-#4564: Register customer serializer to avoid Ray race condition (#4568)
```suggestion
  * FIX-#4564: Register custom serializer to avoid Ray race condition (#4568)
```

2022-06-10 20:36 UTC, naren-ponder approved these changes

2022-06-10 20:40 UTC, RehanSD approved these changes
LGTM!

2022-06-10 20:56 UTC, YarShev approved these changes

2022-06-11 01:58 UTC, devin-petersohn commented
@modin-project/modin-ray is this the recommended way of fixing this? It seems like a bad idea but it is the only way we could use the latest ray release without a race condition

2022-06-11 08:43 UTC, vnlitvinov approved these changes
LGTM, though I would like to find a better way... I wish it existed 😞

2022-06-11 08:44 UTC, vnlitvinov commented
@devin-petersohn a good point here:

> LGTM! We should conduct a perf check to see how pickle compares to Ray's serializer.

Could someone please check some benchmarks?

2022-06-13 04:27 UTC, NickCrews commented
Drive-by-ing here, IDK if you have a good way of running benchmarks, but perhaps the [github-actions bot](https://github.com/dedupeio/dedupe/blob/main/.github/workflows/benchmark-bot.yml) that we wrote for the dedupe library could be useful to you. Take a look at [this comment](https://github.com/dedupeio/dedupe/pull/1062#issuecomment-1152954350) to see how it is used. Makes it really easy for us to test performance changes on a PR.

2022-06-21 15:13 UTC, devin-petersohn commented
Closing because we chose to go a different direction.

2022-06-21 15:13 UTC, closed without merging