REFACTOR: helpers for take_2d_labels_or_positional
modin-project/modin pull request #4865
Opened 2022-08-23 22:02 UTC by jbrockmendel

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

2022-08-29 20:59 UTC, jbrockmendel commented
Looks like `from __future__ import annotations` isnt supported in py36.  any plans to drop support for that?  pandas is already py38+

2022-09-05 19:48 UTC, anmyachev requested changes

2022-09-05 19:48 UTC, anmyachev commented on docs/release_notes/release_notes-0.16.0.rst
> +  * REFACTOR-#0000: Helpers for take_2d_labels_or_positional (#4865)
```suggestion
  * REFACTOR-#4922: Helpers for take_2d_labels_or_positional (#4865)
```

2022-09-05 19:48 UTC, anmyachev commented on modin/core/dataframe/pandas/dataframe/dataframe.py
> +    def _get_new_lengths(self, partitions_dict, *, axis: int) -> List[int]:
Why is an asterisk used here?

2022-09-05 19:48 UTC, anmyachev commented on modin/core/dataframe/pandas/dataframe/dataframe.py
> +            #  is slice
```suggestion
            # is slice
```

2022-09-05 19:48 UTC, anmyachev commented on modin/core/dataframe/pandas/dataframe/dataframe.py
> +    @lazy_metadata_decorator(apply_axis=None)
```suggestion
```

2022-09-06 15:27 UTC, jbrockmendel commented on modin/core/dataframe/pandas/dataframe/dataframe.py
> +    def _get_new_lengths(self, partitions_dict, *, axis: int) -> List[int]:
makes axis keyword-only

2022-09-07 10:14 UTC, anmyachev commented on modin/core/dataframe/pandas/dataframe/dataframe.py
> +    def _get_new_lengths(self, partitions_dict, *, axis: int) -> List[int]:
Got it

2022-09-07 10:18 UTC, anmyachev approved these changes
LGTM!

2022-09-07 10:22 UTC, merged