PERF-#4870: try to avoid index materialization in `__getattribute__`
modin-project/modin pull request #4911
Opened 2022-08-31 22:14 UTC by anmyachev

Signed-off-by: Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #4870 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

2022-09-06 08:15 UTC, anmyachev commented
@vnlitvinov could you review this PR?

2022-09-06 10:40 UTC, vnlitvinov requested changes

2022-09-06 10:40 UTC, vnlitvinov commented on modin/core/storage_formats/base/query_compiler.py
> +        to reduce execution triggering as much as possible.
This docstring is no longer true compared to what we're seeing in the implementation; plus I would rather see this change in PandasQueryCompiler, not BaseQueryCompiler (and leave this as a plain attribute in other places).

2022-09-06 15:19 UTC, vnlitvinov reviewed
Good general idea, I'd like to fix the wording tho.

2022-09-06 15:19 UTC, vnlitvinov commented on modin/core/storage_formats/pandas/query_compiler.py
> +        to reduce execution triggering as much as possible.
```suggestion
        Whether underlying Modin frame should be executed in a lazy mode.

        If True, such QueryCompiler will be handled differently at the front-end in order
        to reduce triggering the computation as much as possible.
```

2022-09-07 10:41 UTC, anmyachev commented
@vnlitvinov let's merge the PR

2022-09-07 11:08 UTC, vnlitvinov approved these changes

2022-09-08 10:56 UTC, anmyachev commented
@mvashishtha could you review?

2022-09-08 16:39 UTC, mvashishtha commented
@anmyachev it looks like the changes to `modin/pandas/base.py` are gone? I just see the PR adding `lazy_execution` but not using it anywhere.

2022-09-08 16:46 UTC, anmyachev commented
> @anmyachev it looks like the changes to `modin/pandas/base.py` are gone? I just see the PR adding `lazy_execution` but not using it anywhere.

It's already used [here](https://github.com/modin-project/modin/blob/5991580cc8ac79c038d6dcde8b02d12feda06109/modin/pandas/base.py#L3174) and [here](https://github.com/modin-project/modin/blob/5991580cc8ac79c038d6dcde8b02d12feda06109/modin/pandas/base.py#L3419).

I just update `lazy_execution` implementation itself.

2022-09-08 16:54 UTC, mvashishtha approved these changes

2022-09-08 16:55 UTC, merged