REFACTOR-#4902: use isort
modin-project/modin pull request #6551
Opened 2023-09-12 14:07 UTC by anmyachev

## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #4902 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

2023-09-12 15:32 UTC, anmyachev commented on .github/workflows/ci.yml
> +      - run: isort . --check-only
I see no reason not to apply `isort` to all Python files in the project. `black` tool can also be applied to all Python files.

2023-09-13 11:45 UTC, dchigarev submitted a review, later dismissed
+1 on these changes from me

2023-09-13 20:00 UTC, vnlitvinov requested changes
Looked through the code, changes LGTM. Still need some fixing of the infra/docs, though...

2023-09-13 20:17 UTC, anmyachev commented on .github/workflows/ci.yml
> +      - run: isort . --check-only
done

2023-09-15 07:34 UTC, vnlitvinov approved these changes
LGTM! But you now have merge conflicts @anmyachev...

2023-09-15 16:10 UTC, dchigarev approved these changes

2023-09-15 16:10 UTC, merged